DROP TABLE IF EXISTS PHOTO;
DROP TABLE IF EXISTS TOPIC;
DROP TABLE IF EXISTS USER_ACCOUNT;

CREATE TABLE USER_ACCOUNT (
  ID SERIAL PRIMARY KEY NOT NULL,
  FULLNAME VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(255) NOT NULL,
  PROFILE_URL VARCHAR(255) NOT NULL
);

CREATE TABLE TOPIC (
  ID INT PRIMARY KEY NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  SLUG VARCHAR(255) NOT NULL
);

CREATE TABLE PHOTO(
  ID INT PRIMARY KEY NOT NULL,
  FULL_URL VARCHAR(255) NOT NULL,
  REGULAR_URL VARCHAR(255) NOT NULL,
  CITY VARCHAR(255) NOT NULL,
  COUNTRY VARCHAR(255) NOT NULL,
  USER_ID INTEGER REFERENCES USER_ACCOUNT(id) ON DELETE CASCADE,
  TOPIC_ID INTEGER REFERENCES TOPIC(id) ON DELETE CASCADE
);

-- db/schema/create.sql

CREATE TABLE IF NOT EXISTS FAVORITES (
  ID SERIAL PRIMARY KEY,
  USER_ID INT,
  PHOTO_ID INT,
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  FOREIGN KEY (PHOTO_ID) REFERENCES PHOTOS(ID)
);
